### ISSUE TITLE
Option to estimate and subtract the background power usage

### ISSUE THREAD

**Issue by lnicola** [lfwa/carbontracker#84]
This can be implemented externally, but here's an idea to make the estimates more precise: sleep for X seconds, measure the power usage, run the task, then subtract the background usage scaled to the duration of the task.

This can it easier to compare different implementations of a task.

**Comment by Snailed** [comment]
Hello @lnicola,
Thanks for your contribution.

This is an interesting idea for users using Carbontracker as a way of estimating the power usage of an application.

Carbontracker has a main design goal of being a tool for estimating the carbon emissions of an application, which should include background power usage to better estimate the entire system. Adding the option to subtract the background usage may cause users to underestimate the carbon emissions of their applications. 
While we acknowledge the usefulness of Carbontracker as a tool for measuring energy consumption, we believe this to be a secondary objective that we do not explicitly support as a feature yet, especially since it is easily implemented externally. Therefore I will close this issue.
